### ISSUE TITLE
Create a shared/static str library so that other projects can link to it

### ISSUE THREAD

**Issue by jetm** [maxim2266/str#2]
Besides copying the two sources code, it would be useful to have a library so other projects can link to it.

**Comment by maxim2266** [comment]
Do you mean static library, or a shared one?

Technically it's possible, but at the moment the library is small and I cannot see any substantial benefit in providing a binary version of it. I think simply adding two source files to a project is much easier than linking to a precompiled binary, also making sure all the compilation options match those of the main project, etc.

**Comment by jetm** [comment]
Both static and shared are beneficial to keep tracking the str version it's been used. But to start with a shared library would be fine. I know the current solution is to put it inside a project, but the str library could be used in several projects, and it's not practical to copy the source code on every project—for example, a Linux distro.

**Comment by maxim2266** [comment]
I don't think it's impractical, after all SQLite project distribute their _entire_ source code in one file, and that simplifies the integrations considerably. Versioning can be handled, for example, via git submodules, like in [this project](https://github.com/maxim2266/OCR). Given all that, I think this library in its current state can be used in the source form, but I may consider adding binaries in the future if this library grows much bigger than it is now, though currently I am not planning any substantial upgrade.

**Comment by DBJDBJ** [comment]
# https://news.ycombinator.com/item?id=16347856
