### ISSUE TITLE
Missing Declaration for _empty_string

### ISSUE THREAD

**Issue by Ralph-Dieter** [maxim2266/str#4]
In file str.h:

Inline function `str_ptr()` may return `_empty_string`, which is defined in str.c, but not declared in str.h.
I assume this will cause a compiler error, if str_ptr() is used.

**Comment by maxim2266** [comment]
```C
static inline
const char* str_ptr(const str s)
{
	extern const char* const _empty_string;

	return s.ptr ? s.ptr : _empty_string;
}
```
It is declared as `extern` right inside the function.

**Comment by Ralph-Dieter** [comment]
Of course it is. I must have been blind. 
I'm sorry for bothering you.
